name: ed
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip # no specific version since we regulary update it
  - ipykernel=7.1
  - matplotlib=3.10
  - numpy=2.3
  - scipy=1.16
  - pytest=8.4
  - pytest-cov=7.0
  
  
  - pip:
      - hydra-core==1.3
      - pyyaml==6.0
