[project]
name = "ed"
version = "0.1.0"
description = "A small package for using exact diagonalization. Note, that this is part of the larger project ??."
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


