# Configuration file for the XXZ cavity model experiments
# Lets see how I will structure the configuration settings :)


defaults:
  - method: exact_diagonalization
  - _self_

system:
  L: 4 # number of lattice sites
  N_f: null # number of fermions (null for half-filling)
  N_ph: 2 # maximal number of photons in the cavity
  boundary_conditions: "periodic"

sweeps:
  U_sweep:
    parameters:
      # Set the fixed parameters for the sweep
      t: 1.0 # hopping amplitude
      g: 0.5 # light-matter coupling strength
      omega: 10.0 # cavity frequency
      
      # set range for U sweep
      U_min: 0.0
      U_max: 20.0
      U_points: 100
    observables:
      - photon_number
      - entanglement_entropy

  omega_sweep:
    parameters:
      # Set the fixed parameters for the sweep
      t: 1.0 # hopping amplitude
      g: 0.5 # light-matter coupling strength
      U: 3.0 # nearest neighbor interaction

      # set range for omega sweep
      omega_min: 1.0
      omega_max: 100.0
      omega_points: 13

    observables:
      - photon_number
      - entanglement_entropy


seed: 42
root_data_dir: /data/xxz_cavity/${method.name}/
