name: nqs
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip # no specific version since we regulary update it
  - ipykernel=7.1 # for jupyter notebook support
  - pytest=8.4
  - pytest-cov=7.0


  - pip:
    - netket==3.21
