# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI - ed 

# Define when the workflow should run
on:
  push:
    paths:
      - 'methods/ed/**'
    branches:  
      - "main"
  pull_request:
    paths:
      - 'methods/ed/**'
  workflow_dispatch:

permissions:
  contents: read

# Define which jobs should be executed
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Miniconda with conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: ed
        environment-file: methods/ed/environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Install package and dependencies
      # ensure that environment is active and packages are on path
      shell: bash -l {0}
      run: |
        cd methods/ed
        python -m pip install --upgrade pip
        pip install -e .
        pip install flake8 

    - name: Lint with flake8 (syntax checking)
      # ensure that environment is active and packages are on path
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    
    - name: Run tests with pytest in conda environment
      # ensure that environment is active and packages are on path
      shell: bash -l {0}
      run: |
        cd methods/ed
        pytest --cov=src --cov-report=xml --cov-report=term-missing -s

    - name: Upload Python coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: methods/ed/coverage.xml
        flags: ed
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

