# This workflow will run the tests of the package on multiple operating systems
# It was taken from https://bjack205.github.io/JuliaTemplateRepo.jl/dev/CI.html 

name: Julia application - Dmrg
on:
  push:
    paths: 
      - 'methods/Dmrg/**'
    branches:
      - main
  pull_request:
    paths: 
      - 'methods/Dmrg/**'
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/julia-buildpkg@v1
        with:
          julia-version: ${{ matrix.julia-version }}

      - name: Run tests with coverage
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: true

      # Use Coverage.jl with official uploader to codecov.io
      - name: Process and upload coverage with Coverage.jl
        run: |
          julia -e '
            using Pkg; Pkg.add("Coverage")
            using Coverage
            process_and_upload(service=:codecov, folder="src")
          '