# This workflow will run the tests of the package on multiple operating systems
# It was taken from https://bjack205.github.io/JuliaTemplateRepo.jl/dev/CI.html 

name: Julia application - Dmrg
on:
  push:
    paths: 
      - 'methods/Dmrg/**'
    branches:
      - main
  pull_request:
    paths: 
      - 'methods/Dmrg/**'
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.12'
        os: ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          working-directory: methods/Dmrg

      - uses: julia-actions/julia-runtest@latest
        with:
          working-directory: methods/Dmrg
      
      - uses: julia-actions/julia-uploadcodecov@latest
        with:
          working-directory: methods/Dmrg
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}