# This workflow will run the tests of the package on multiple operating systems
# It was taken from https://bjack205.github.io/JuliaTemplateRepo.jl/dev/CI.html 

name: Julia application - Dmrg
on:
  push:
    paths: 
      - 'methods/Dmrg/**'
    branches:
      - main
  pull_request:
    paths: 
      - 'methods/Dmrg/**'
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.12']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - name: Install Dependencies
        run: julia --project=methods/Dmrg -e 'using Pkg; Pkg.instantiate()'

      - name: Run Tests
        run: julia --project=methods/Dmrg -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: methods/Dmrg/coverage/coverage.xml
          fail_ci_if_error: true


      # - name: Upload coverage to Codecov
      #   uses: julia-actions/julia-uploadcodecov@latest
      #   with:
      #     working-directory: methods/Dmrg